<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $title ?? 'Advanced Report' }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #0f172a; font-size: 12px; }
        .header { border: 1px solid #d1fae5; background: #f0fdf4; padding: 12px 14px; margin-bottom: 12px; }
        .title { font-size: 18px; font-weight: 700; margin: 0 0 4px; }
        .meta { font-size: 11px; color: #334155; margin: 2px 0; }
        .summary { margin: 0 0 12px; border-collapse: collapse; width: 100%; }
        .summary td { border: 1px solid #cbd5e1; padding: 8px; width: 25%; }
        .label { font-size: 10px; color: #475569; text-transform: uppercase; }
        .value { font-size: 16px; font-weight: 700; margin-top: 4px; }
        table.report { border-collapse: collapse; width: 100%; }
        table.report th { background: #0f172a; color: #fff; font-size: 10px; text-transform: uppercase; padding: 7px; text-align: left; }
        table.report td { border: 1px solid #cbd5e1; padding: 6px; vertical-align: top; }
        .muted { color: #64748b; font-size: 10px; margin-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <p class="title">{{ $title ?? 'Advanced Report' }}</p>
        <p class="meta"><strong>Workspace:</strong> {{ $tenantName ?? 'Workspace' }} ({{ $tenantDomain ?? 'tenant' }})</p>
        <p class="meta"><strong>Coverage:</strong> {{ $periodLabel ?? 'Custom period' }}</p>
        <p class="meta"><strong>Generated:</strong> {{ ($generatedAt ?? now())->format('M d, Y h:i A') }}</p>
    </div>

    <table class="summary">
        <tr>
            <td>
                <div class="label">Total Tasks</div>
                <div class="value">{{ number_format((int) ($summary['total_tasks'] ?? 0)) }}</div>
            </td>
            <td>
                <div class="label">Completed</div>
                <div class="value">{{ number_format((int) ($summary['completed'] ?? 0)) }}</div>
            </td>
            <td>
                <div class="label">Overdue</div>
                <div class="value">{{ number_format((int) ($summary['overdue'] ?? 0)) }}</div>
            </td>
            <td>
                <div class="label">Open / Due Today</div>
                <div class="value">{{ number_format((int) ($summary['open'] ?? 0)) }}</div>
            </td>
        </tr>
    </table>

    <table class="report">
        <thead>
            <tr>
                <th style="width:6%;">ID</th>
                <th style="width:26%;">Task</th>
                <th style="width:14%;">Board</th>
                <th style="width:12%;">Stage</th>
                <th style="width:10%;">Status</th>
                <th style="width:10%;">Due Date</th>
                <th style="width:11%;">Created</th>
                <th style="width:11%;">Updated</th>
            </tr>
        </thead>
        <tbody>
            @forelse($rows ?? [] as $row)
                <tr>
                    <td>{{ $row->id }}</td>
                    <td>{{ $row->title }}</td>
                    <td>{{ $row->board_name }}</td>
                    <td>{{ $row->stage_name }}</td>
                    <td>{{ $row->status }}</td>
                    <td>{{ $row->due_date }}</td>
                    <td>{{ $row->created_at }}</td>
                    <td>{{ $row->updated_at }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="8">No report records available for this period.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <p class="muted">Detailed task export generated by NSync for workspace reporting and review.</p>
</body>
</html>
