<div class="cover-page">
    <div class="cover-graphic"></div>
    <div class="cover-copy">
        <p class="cover-tag">NSync</p>
        <h1 class="cover-title">{{ $title ?? 'Workspace Report' }}</h1>
        <p class="cover-description">{{ $reportPurpose ?? 'Workspace report generated by NSync.' }}</p>
        <div class="cover-meta">
            <p><strong>Prepared by:</strong> {{ $preparedBy ?? ($tenantName ?? 'Workspace Admin') }}</p>
            <p><strong>Date of submission:</strong> {{ ($generatedAt ?? now())->format('F d, Y') }}</p>
            <p><strong>Workspace:</strong> {{ $tenantName ?? 'Workspace' }} ({{ $tenantDomain ?? 'tenant' }})</p>
        </div>
    </div>
</div>
<div class="page-break"></div>
